POST http://localhost:5000/user
Content-Type: application/json

{
    "id": 1,
    "name": "user1",
    "email": "email1",
    "mobile": "mobile1",
    "birthday": "birthday1",
    "address": "address1",
}


###
DELETE  http://localhost:5000/user
Content-Type: application/json

{
    "id":1
}